In [37]:
# Importing the  required libraries
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [38]:
# Creating the environment
env=gym.make('FrozenLake-v0')

In [39]:
# Creating the Q_table
action_space_size=env.action_space.n
state_space_size=env.observation_space.n
q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
# Parameter Initialization
num_episodes = 20000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [43]:
# Implementation of Q-learning algorithm
rewards_all_episodes=[]
for episode in range(num_episodes):
    state=env.reset()
    done=False
    rewards_current_episode=0
    
    for step in range(max_steps_per_episode):
        # Exploration and exploitaion trade-off
        exploration_rate_threshold=random.uniform(0,1)
        if exploration_rate_threshold>exploration_rate:
            action=np.argmax(q_table[state,:])
        else:
            action=env.action_space.sample()
        
        new_state, reward, done, info=env.step(action)
        #Update Q-value 
        q_table[state,action]=q_table[state,action]*(1-learning_rate)+learning_rate*(reward + discount_rate * np.max(q_table[new_state, :]))
        
        state=new_state
        rewards_current_episode+= reward
        
        if done==True:
            break
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)
# The calcualtion of rewards per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count=1000
print("An average reward per thousand episode")
for r in rewards_per_thousand_episodes:
    
    print(count, "--",(sum(r/1000)))
    count=count+1000
print("The updated version of Q-table")
print(q_table)


An average reward per thousand episode
1000 -- 0.06500000000000004
2000 -- 0.21100000000000016
3000 -- 0.4060000000000003
4000 -- 0.5470000000000004
5000 -- 0.6170000000000004
6000 -- 0.6230000000000004
7000 -- 0.6650000000000005
8000 -- 0.6690000000000005
9000 -- 0.6950000000000005
10000 -- 0.6900000000000005
11000 -- 0.7000000000000005
12000 -- 0.6960000000000005
13000 -- 0.6540000000000005
14000 -- 0.6790000000000005
15000 -- 0.6720000000000005
16000 -- 0.6860000000000005
17000 -- 0.6890000000000005
18000 -- 0.6770000000000005
19000 -- 0.6960000000000005
20000 -- 0.6940000000000005
The updated version of Q-table
[[0.52937595 0.52812849 0.52794514 0.52476293]
 [0.3836632  0.30875556 0.28383789 0.51453326]
 [0.42957164 0.43115323 0.40271509 0.49617091]
 [0.36529069 0.3297155  0.22607682 0.47368656]
 [0.54566397 0.30774747 0.29974734 0.34341897]
 [0.         0.         0.         0.        ]
 [0.33434691 0.12258344 0.18201361 0.1010013 ]
 [0.         0.         0.         0.        ]
 

In [46]:
# Watching the agent play game 
for episode in range(3):
    state=env.reset()
    done=False
    print("###","Episode no.",episode+1,"####")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action=np.argmax(q_table[state,:])
        new_state, reward, done, info=env.step(action)
        if done:
            clear_output(wait=True)
            env.render()
            if reward==1:
                print("@@@Mission Accomplished@@@")
                time.sleep(3)
            else:
                print("*** Nashrudin fell into a well****")
                time.sleep(3)
            clear_output(wait=True)
            break
        state=new_state
    env.close()
        

  (Right)
SFFF
FHFH
FFFH
HFFG
@@@Mission Accomplished@@@
