In [2]:
import numpy as np
A=np.array([[56, 0, 4.4, 68],
            [1.2, 104, 52, 8],
            [1.8, 135, 99, 0.9]
           ])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal= A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [4]:
percentage= 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [6]:
# Construction of vectors in python/numpy# 5 random gaussian variable
a=np.random.randn(5)
print(a)

[ 0.83746251 -0.47903091 -0.08321613 -1.3841581  -1.09631856]


In [7]:
print(a.shape)

(5,)


In [8]:
print(a.T)

[ 0.83746251 -0.47903091 -0.08321613 -1.3841581  -1.09631856]


In [9]:
print(np.dot(a,a.T))

4.0555470214107165


In [10]:
a=np.random.randn(5,1)

In [11]:
print(a.T)

[[-1.86046476  0.66567547  1.12130606 -0.71191023  0.00444451]]


In [12]:
print(np.dot(a,a.T))

[[ 3.46132914e+00 -1.23846576e+00 -2.08615041e+00  1.32448389e+00
  -8.26885143e-03]
 [-1.23846576e+00  4.43123832e-01  7.46425939e-01 -4.73901175e-01
   2.95860028e-03]
 [-2.08615041e+00  7.46425939e-01  1.25732728e+00 -7.98269250e-01
   4.98365430e-03]
 [ 1.32448389e+00 -4.73901175e-01 -7.98269250e-01  5.06816170e-01
  -3.16409104e-03]
 [-8.26885143e-03  2.95860028e-03  4.98365430e-03 -3.16409104e-03
   1.97536557e-05]]


In [16]:
import torch

ModuleNotFoundError: No module named 'torch'