In [1]:
pip install gym

     |████████████████████████████████| 1.6MB 482kB/s eta 0:00:01
     |████████████████████████████████| 27.4MB 563kB/s eta 0:00:01
     |████████████████████████████████| 1.0MB 1.7MB/s eta 0:00:01
     |████████████████████████████████| 2.2MB 2.0MB/s eta 0:00:01
     |████████████████████████████████| 829kB 2.4MB/s eta 0:00:01
  Stored in directory: /home/dell/snap/jupyter/6/.cache/pip/wheels/be/85/3b/480b828a4a697b37392740a040b8989f729d952b4e441a1877
  Stored in directory: /home/dell/snap/jupyter/6/.cache/pip/wheels/8b/99/a0/81daf51dcd359a9377b110a8a886b3895921802d2fc1b2397e
Successfully built gym future
Note: you may need to restart the kernel to use updated packages.


In [4]:
# Importing the  required libraries
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [5]:
# Creating the environment
env=gym.make('FrozenLake-v0')

In [6]:
# Creating the Q_table
action_space_size=env.action_space.n
state_space_size=env.observation_space.n
q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# Parameter Initialization
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [12]:
# Implementation of Q-learning algorithm
rewards_all_episodes=[]
for episode in range(num_episodes):
    state=env.reset()
    done=False
    rewards_current_episode=0
    
    for steps in range(max_steps_per_episode):
        # Exploration and exploitaion trade-off
        exploration_rate_threshold=random.uniform(0,1)
        if exploration_rate_threshold>exploration_rate:
            action=np.argmax(q_table[state,:])
        else:
            action=env.action_space.sample()
        
        new_state, reward, done, info=env.step(action)
        #Update Q-value 
        q_table[state,action]=q_table[state,action]*(1-learning_rate)+learning_rate*(reward + discount_rate * np.max(q_table[new_state, :]))
        
        state=new_state
        rewards_current_episode+= reward
        
        if done==True:
            break
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)
# The calcualtion of rewards per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count=1000
print("An average reward per thousand episode")
for r in rewards_per_thousand_episodes:
    
    print(count, "--",(sum(r/1000)))
    count=count+1000
print("The updated version of Q-table")
print(q_table)


An average reward per thousand episode
1000 -- 0.5100000000000003
2000 -- 0.6860000000000005
3000 -- 0.6800000000000005
4000 -- 0.6830000000000005
5000 -- 0.7150000000000005
6000 -- 0.7190000000000005
7000 -- 0.6770000000000005
8000 -- 0.6650000000000005
9000 -- 0.6830000000000005
10000 -- 0.7090000000000005
The updated version of Q-table
[[0.5619417  0.52074333 0.52308623 0.5266887 ]
 [0.33702785 0.345486   0.32235424 0.50877577]
 [0.42581477 0.40307279 0.4242737  0.47861976]
 [0.32750619 0.2512367  0.32178408 0.46027995]
 [0.58042353 0.46241195 0.3940604  0.39466907]
 [0.         0.         0.         0.        ]
 [0.18944174 0.15338907 0.4132777  0.10963841]
 [0.         0.         0.         0.        ]
 [0.40728548 0.4653679  0.48897181 0.634066  ]
 [0.31968037 0.6763655  0.53148344 0.34865316]
 [0.64674029 0.44003105 0.42749247 0.26132381]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.43523113 0.53154118 0.82908745 0.46308076]
 